export declare const DEFAULT_LOCAL_FORMATS: {
    decimal: string;
    thousands: string;
    grouping: number[];
    currency: string[];
    dateTime: string;
    date: string;
    dateSeparator: string;
    time: string;
    periods: string[];
    days: string[];
    shortDays: string[];
    months: string[];
    shortMonths: string[];
    levels: string[];
    shortLevels: string[];
    durationLongSuffix: string[];
    durationShortSuffix: string[];
    multi: string[];
};
